
```{r}
library(tidyverse)
library(feather)
library(magrittr)
library(usmap)
library(rgdal)
library(leaflet)
library(geosphere)
library(RColorBrewer)

params <- list()
params$reception_prop = 0.4 #proportion of evacuees who go to counties with reception centers
```

```{r}
scenarios <- read_feather("./scenarios.feather")
hazard <- read_feather("./hazard.feather")
county_desc <- read_feather("./county_desc.feather")

texas_sf = readOGR("./shapefiles/County.shp")

texas_sf@data = texas_sf@data %>% 
  mutate(
    fips = as.character(CNTY_FIPS),
    lon = map_dbl(texas_sf@polygons, ~ .x@labpt[1]),
    lat = map_dbl(texas_sf@polygons, ~ .x@labpt[2]),
    label = sprintf("%s, %s (%s)", CNTY_NM, DIST_NM, fips)
  )

texas_fips <- county_desc %>% 
  filter(state_code == "TX") %>% pull(fips)

scenarios %<>% 
  left_join(hazard %>% 
              select(-county) %>% 
              rename(source_fips = fips))
```


```{r}
scenario_ <- "1"

county_map <- scenarios %>% 
  filter(scenario == scenario_) %>% 
  select(-target_county, -target_fips) %>% 
  distinct_all() %>% 
  mutate(evacuee_prop = prop_voluntary,  
         evacuee_prop = if_else(evacuation_type == "mandatory", 
                                prop_mandatory, evacuee_prop), 
         evacuee_prop = if_else(source_fips == "48201", 
                                evacuee_prop * 0.1, 
                                evacuee_prop),
         evacuations = evacuee_prop * source_pop, 
         exportations = evacuations * prevalence) %>% 
  rename(fips = source_fips)

county_map %>% 
  select(source_county, source_pop, evacuation_type, evacuee_prop, evacuations, exportations) %>% 
  arrange(desc(evacuations))

texas_sf@data = texas_sf@data %>% 
  left_join(select(county_map, fips, evacuation_type), by="fips")

sum(county_map$evacuations, na.rm = TRUE)

plot_usmap(data = county_map, 
           include = texas_fips,
           values = "evacuations")
```


```{r, fig.width=6, fig.height=4}
pal = colorFactor('Reds', domain = texas_sf@data$evacuation_type)

leaflet(
  texas_sf,
  options = leafletOptions(
    zoomControl = FALSE,
    minZoom = 5,
    maxZoom = 7,
    attributionControl = FALSE
  )
) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(
    weight = 0.5,
    color = "black",
    smoothFactor = 0.5,
    fillColor = pal(texas_sf@data$evacuation_type),
    label = ~ label,
    fillOpacity = 0.5
  ) %>% 
  setMaxBounds(
    lng1 = -106.74,
    lat1 = 25.87,
    lng2 = -93.4,
    lat2 = 36.6
  )  %>% 
  addLegend(
    title = "Evacuation type", 
    'bottomright',
    pal = pal,
    values = ~ texas_sf@data$evacuation_type
  )
```

```{r}
scenarios %<>% 
  group_by(scenario, source_fips) %>% 
  mutate(reception_prop = 1/n()) %>% 
  ungroup() %>% 
  mutate(evacuee_prop = prop_voluntary,  
         evacuee_prop = if_else(evacuation_type == "mandatory", 
                                prop_mandatory, evacuee_prop), 
         evacuee_prop = if_else(source_fips == "48201", 
                                evacuee_prop * 0.1, 
                                evacuee_prop),
         evacuees = evacuee_prop * source_pop * reception_prop, 
         exportations = evacuees * prevalence)
```

```{r}
scenario_ <- "1" 

county_map <- scenarios %>% 
  filter(scenario == 1) %>% 
  group_by(target_fips, target_county) %>% 
  summarise(receptions = sum(evacuees) * params$reception_prop, 
            importations = sum(exportations) * params$reception_prop) %>% 
  rename(fips = target_fips)

county_map

sum(county_map$receptions)

plot_usmap(data = county_map, 
           include = texas_fips,
           values = "receptions")
```

```{r}
plots <- list()
for(x in sort(unique(scenarios$scenario))) {
  county_map <- scenarios %>% 
  filter(scenario == x) %>% 
  group_by(target_fips, target_county) %>% 
  summarise(importations = sum(exportations) * params$reception_prop) %>% 
  rename(fips = target_fips)
  
  plots[[x]] <- plot_usmap(data = county_map, 
                           include = texas_fips, 
                           values = "importations") + 
    labs(title = x)
}
plots
```

```{r}
lon_map = setNames(texas_sf@data$lon, texas_sf@data$fips)
lat_map = setNames(texas_sf@data$lat, texas_sf@data$fips)
lab_map = setNames(texas_sf@data$CNTY_NM, texas_sf@data$fips)
dist_map = setNames(texas_sf@data$DIST_NM, texas_sf@data$fips)
src = tibble(
  lon=lon_map[scenarios$source_fips],
  lat=lat_map[scenarios$source_fips]
)
dst = tibble(
  lon=lon_map[scenarios$target_fips],
  lat=lat_map[scenarios$target_fips]
)
flows = gcIntermediate(src, dst, sp = TRUE, addStartEnd = TRUE)
flows$src = scenarios$source_fips
flows$dst = scenarios$target_fips
flows$district = dist_map[scenarios$target_fips]
flows$exportations = scenarios$exportations
flows$label = sprintf(
  "%s -> %s: %.2f",
  lab_map[flows$src],
  lab_map[flows$dst],
  flows$exportations
)
```


```{r}
pal = colorFactor(brewer.pal(4, 'Set2'), flows$district)

flows$exportations_ = 1.0 + sqrt(flows$exportations)
flows$exportations_ = 5 * flows$exportations_ / max(flows$exportations_)

leaflet(
  options = leafletOptions(
    zoomControl = FALSE,
    minZoom = 6,
    maxZoom = 8,
    attributionControl = FALSE
  )
) %>%
  addProviderTiles(providers$CartoDB.DarkMatter) %>%
  addPolygons(
    data = subset(texas_sf, fips %in% flows$src),
    weight = 0.5,
    color = "lightblue",
    smoothFactor = 0.5,
    fillColor = "black",  # pal(texas_sf@data$evacuation_type),
    label = ~ label,
    fillOpacity = 0.0
  ) %>% 
  addPolylines(
    data = flows,
    weight = ~ exportations_,
    color = ~pal(district),
    group = ~ district,
    # weight = 1.0,
    opacity = 1.0,
    label = ~ label
  ) %>% 
  setMaxBounds(
    lng1 = -106.24,
    lat1 = 25.87,
    lng2 = -92.4,
    lat2 = 36.6
  ) %>%
  addLayersControl(
    position = "topleft",
    overlayGroups = unique(flows$district), 
    options = layersControlOptions(collapsed = FALSE)
  )
#  %>% 
  # addLegend(
  #   title = "Exportations", 
  #   'bottomright',
  #   pal = pal,
  #   values =  log10(1 + flows$exportations)
  # )
```

